-- Journal funding models and public program directory changes atomically.
INSERT INTO change_journal_coverage VALUES('funding_awards','["id", "awarding_agency_id", "award_identifier", "recipient_organization_id", "recipient_uei", "assistance_listing_number", "source_url", "evidence"]','[]');
CREATE TRIGGER "journal_funding_awards_insert" AFTER INSERT ON "funding_awards"
WHEN NOT EXISTS(SELECT 1 FROM organization_replica_state WHERE source IS NOT NULL)
BEGIN INSERT INTO change_journal(table_name,record_key,operation,before_json,after_json)
 VALUES('funding_awards',json_object('id',NEW."id"),'insert',NULL,json_object('id',NEW."id",'awarding_agency_id',NEW."awarding_agency_id",'award_identifier',NEW."award_identifier",'recipient_organization_id',NEW."recipient_organization_id",'recipient_uei',NEW."recipient_uei",'assistance_listing_number',NEW."assistance_listing_number",'source_url',NEW."source_url",'evidence',NEW."evidence")); END;
CREATE TRIGGER "journal_funding_awards_update" AFTER UPDATE ON "funding_awards"
WHEN NOT EXISTS(SELECT 1 FROM organization_replica_state WHERE source IS NOT NULL) AND NOT(OLD."id" IS NEW."id" AND OLD."awarding_agency_id" IS NEW."awarding_agency_id" AND OLD."award_identifier" IS NEW."award_identifier" AND OLD."recipient_organization_id" IS NEW."recipient_organization_id" AND OLD."recipient_uei" IS NEW."recipient_uei" AND OLD."assistance_listing_number" IS NEW."assistance_listing_number" AND OLD."source_url" IS NEW."source_url" AND OLD."evidence" IS NEW."evidence")
BEGIN INSERT INTO change_journal(table_name,record_key,operation,before_json,after_json)
 VALUES('funding_awards',json_object('id',NEW."id"),'update',json_object('id',OLD."id",'awarding_agency_id',OLD."awarding_agency_id",'award_identifier',OLD."award_identifier",'recipient_organization_id',OLD."recipient_organization_id",'recipient_uei',OLD."recipient_uei",'assistance_listing_number',OLD."assistance_listing_number",'source_url',OLD."source_url",'evidence',OLD."evidence"),json_object('id',NEW."id",'awarding_agency_id',NEW."awarding_agency_id",'award_identifier',NEW."award_identifier",'recipient_organization_id',NEW."recipient_organization_id",'recipient_uei',NEW."recipient_uei",'assistance_listing_number',NEW."assistance_listing_number",'source_url',NEW."source_url",'evidence',NEW."evidence")); END;
CREATE TRIGGER "journal_funding_awards_delete" AFTER DELETE ON "funding_awards"
WHEN NOT EXISTS(SELECT 1 FROM organization_replica_state WHERE source IS NOT NULL)
BEGIN INSERT INTO change_journal(table_name,record_key,operation,before_json,after_json)
 VALUES('funding_awards',json_object('id',OLD."id"),'delete',json_object('id',OLD."id",'awarding_agency_id',OLD."awarding_agency_id",'award_identifier',OLD."award_identifier",'recipient_organization_id',OLD."recipient_organization_id",'recipient_uei',OLD."recipient_uei",'assistance_listing_number',OLD."assistance_listing_number",'source_url',OLD."source_url",'evidence',OLD."evidence"),NULL); END;
INSERT INTO change_journal_coverage VALUES('funding_entities','["organization_id", "entity_type", "administering_organization_id", "legal_entity_organization_id", "treasury_account_symbol", "source_url", "evidence", "reviewed_at"]','[]');
CREATE TRIGGER "journal_funding_entities_insert" AFTER INSERT ON "funding_entities"
WHEN NOT EXISTS(SELECT 1 FROM organization_replica_state WHERE source IS NOT NULL)
BEGIN INSERT INTO change_journal(table_name,record_key,operation,before_json,after_json)
 VALUES('funding_entities',json_object('organization_id',NEW."organization_id"),'insert',NULL,json_object('organization_id',NEW."organization_id",'entity_type',NEW."entity_type",'administering_organization_id',NEW."administering_organization_id",'legal_entity_organization_id',NEW."legal_entity_organization_id",'treasury_account_symbol',NEW."treasury_account_symbol",'source_url',NEW."source_url",'evidence',NEW."evidence",'reviewed_at',NEW."reviewed_at")); END;
CREATE TRIGGER "journal_funding_entities_update" AFTER UPDATE ON "funding_entities"
WHEN NOT EXISTS(SELECT 1 FROM organization_replica_state WHERE source IS NOT NULL) AND NOT(OLD."organization_id" IS NEW."organization_id" AND OLD."entity_type" IS NEW."entity_type" AND OLD."administering_organization_id" IS NEW."administering_organization_id" AND OLD."legal_entity_organization_id" IS NEW."legal_entity_organization_id" AND OLD."treasury_account_symbol" IS NEW."treasury_account_symbol" AND OLD."source_url" IS NEW."source_url" AND OLD."evidence" IS NEW."evidence" AND OLD."reviewed_at" IS NEW."reviewed_at")
BEGIN INSERT INTO change_journal(table_name,record_key,operation,before_json,after_json)
 VALUES('funding_entities',json_object('organization_id',NEW."organization_id"),'update',json_object('organization_id',OLD."organization_id",'entity_type',OLD."entity_type",'administering_organization_id',OLD."administering_organization_id",'legal_entity_organization_id',OLD."legal_entity_organization_id",'treasury_account_symbol',OLD."treasury_account_symbol",'source_url',OLD."source_url",'evidence',OLD."evidence",'reviewed_at',OLD."reviewed_at"),json_object('organization_id',NEW."organization_id",'entity_type',NEW."entity_type",'administering_organization_id',NEW."administering_organization_id",'legal_entity_organization_id',NEW."legal_entity_organization_id",'treasury_account_symbol',NEW."treasury_account_symbol",'source_url',NEW."source_url",'evidence',NEW."evidence",'reviewed_at',NEW."reviewed_at")); END;
CREATE TRIGGER "journal_funding_entities_delete" AFTER DELETE ON "funding_entities"
WHEN NOT EXISTS(SELECT 1 FROM organization_replica_state WHERE source IS NOT NULL)
BEGIN INSERT INTO change_journal(table_name,record_key,operation,before_json,after_json)
 VALUES('funding_entities',json_object('organization_id',OLD."organization_id"),'delete',json_object('organization_id',OLD."organization_id",'entity_type',OLD."entity_type",'administering_organization_id',OLD."administering_organization_id",'legal_entity_organization_id',OLD."legal_entity_organization_id",'treasury_account_symbol',OLD."treasury_account_symbol",'source_url',OLD."source_url",'evidence',OLD."evidence",'reviewed_at',OLD."reviewed_at"),NULL); END;
INSERT INTO change_journal_coverage VALUES('funding_facts','["id", "support_record_id", "fact_type", "scope", "amount", "currency", "measurement", "fiscal_year", "fiscal_year_basis", "period_start", "period_end", "reporting_date", "administering_agency_id", "program_organization_id", "fund_organization_id", "account_organization_id", "award_id", "included_in_fact_id", "supersedes_fact_id", "source_url", "evidence", "reviewed_at"]','[]');
CREATE TRIGGER "journal_funding_facts_insert" AFTER INSERT ON "funding_facts"
WHEN NOT EXISTS(SELECT 1 FROM organization_replica_state WHERE source IS NOT NULL)
BEGIN INSERT INTO change_journal(table_name,record_key,operation,before_json,after_json)
 VALUES('funding_facts',json_object('id',NEW."id"),'insert',NULL,json_object('id',NEW."id",'support_record_id',NEW."support_record_id",'fact_type',NEW."fact_type",'scope',NEW."scope",'amount',NEW."amount",'currency',NEW."currency",'measurement',NEW."measurement",'fiscal_year',NEW."fiscal_year",'fiscal_year_basis',NEW."fiscal_year_basis",'period_start',NEW."period_start",'period_end',NEW."period_end",'reporting_date',NEW."reporting_date",'administering_agency_id',NEW."administering_agency_id",'program_organization_id',NEW."program_organization_id",'fund_organization_id',NEW."fund_organization_id",'account_organization_id',NEW."account_organization_id",'award_id',NEW."award_id",'included_in_fact_id',NEW."included_in_fact_id",'supersedes_fact_id',NEW."supersedes_fact_id",'source_url',NEW."source_url",'evidence',NEW."evidence",'reviewed_at',NEW."reviewed_at")); END;
CREATE TRIGGER "journal_funding_facts_update" AFTER UPDATE ON "funding_facts"
WHEN NOT EXISTS(SELECT 1 FROM organization_replica_state WHERE source IS NOT NULL) AND NOT(OLD."id" IS NEW."id" AND OLD."support_record_id" IS NEW."support_record_id" AND OLD."fact_type" IS NEW."fact_type" AND OLD."scope" IS NEW."scope" AND OLD."amount" IS NEW."amount" AND OLD."currency" IS NEW."currency" AND OLD."measurement" IS NEW."measurement" AND OLD."fiscal_year" IS NEW."fiscal_year" AND OLD."fiscal_year_basis" IS NEW."fiscal_year_basis" AND OLD."period_start" IS NEW."period_start" AND OLD."period_end" IS NEW."period_end" AND OLD."reporting_date" IS NEW."reporting_date" AND OLD."administering_agency_id" IS NEW."administering_agency_id" AND OLD."program_organization_id" IS NEW."program_organization_id" AND OLD."fund_organization_id" IS NEW."fund_organization_id" AND OLD."account_organization_id" IS NEW."account_organization_id" AND OLD."award_id" IS NEW."award_id" AND OLD."included_in_fact_id" IS NEW."included_in_fact_id" AND OLD."supersedes_fact_id" IS NEW."supersedes_fact_id" AND OLD."source_url" IS NEW."source_url" AND OLD."evidence" IS NEW."evidence" AND OLD."reviewed_at" IS NEW."reviewed_at")
BEGIN INSERT INTO change_journal(table_name,record_key,operation,before_json,after_json)
 VALUES('funding_facts',json_object('id',NEW."id"),'update',json_object('id',OLD."id",'support_record_id',OLD."support_record_id",'fact_type',OLD."fact_type",'scope',OLD."scope",'amount',OLD."amount",'currency',OLD."currency",'measurement',OLD."measurement",'fiscal_year',OLD."fiscal_year",'fiscal_year_basis',OLD."fiscal_year_basis",'period_start',OLD."period_start",'period_end',OLD."period_end",'reporting_date',OLD."reporting_date",'administering_agency_id',OLD."administering_agency_id",'program_organization_id',OLD."program_organization_id",'fund_organization_id',OLD."fund_organization_id",'account_organization_id',OLD."account_organization_id",'award_id',OLD."award_id",'included_in_fact_id',OLD."included_in_fact_id",'supersedes_fact_id',OLD."supersedes_fact_id",'source_url',OLD."source_url",'evidence',OLD."evidence",'reviewed_at',OLD."reviewed_at"),json_object('id',NEW."id",'support_record_id',NEW."support_record_id",'fact_type',NEW."fact_type",'scope',NEW."scope",'amount',NEW."amount",'currency',NEW."currency",'measurement',NEW."measurement",'fiscal_year',NEW."fiscal_year",'fiscal_year_basis',NEW."fiscal_year_basis",'period_start',NEW."period_start",'period_end',NEW."period_end",'reporting_date',NEW."reporting_date",'administering_agency_id',NEW."administering_agency_id",'program_organization_id',NEW."program_organization_id",'fund_organization_id',NEW."fund_organization_id",'account_organization_id',NEW."account_organization_id",'award_id',NEW."award_id",'included_in_fact_id',NEW."included_in_fact_id",'supersedes_fact_id',NEW."supersedes_fact_id",'source_url',NEW."source_url",'evidence',NEW."evidence",'reviewed_at',NEW."reviewed_at")); END;
CREATE TRIGGER "journal_funding_facts_delete" AFTER DELETE ON "funding_facts"
WHEN NOT EXISTS(SELECT 1 FROM organization_replica_state WHERE source IS NOT NULL)
BEGIN INSERT INTO change_journal(table_name,record_key,operation,before_json,after_json)
 VALUES('funding_facts',json_object('id',OLD."id"),'delete',json_object('id',OLD."id",'support_record_id',OLD."support_record_id",'fact_type',OLD."fact_type",'scope',OLD."scope",'amount',OLD."amount",'currency',OLD."currency",'measurement',OLD."measurement",'fiscal_year',OLD."fiscal_year",'fiscal_year_basis',OLD."fiscal_year_basis",'period_start',OLD."period_start",'period_end',OLD."period_end",'reporting_date',OLD."reporting_date",'administering_agency_id',OLD."administering_agency_id",'program_organization_id',OLD."program_organization_id",'fund_organization_id',OLD."fund_organization_id",'account_organization_id',OLD."account_organization_id",'award_id',OLD."award_id",'included_in_fact_id',OLD."included_in_fact_id",'supersedes_fact_id',OLD."supersedes_fact_id",'source_url',OLD."source_url",'evidence',OLD."evidence",'reviewed_at',OLD."reviewed_at"),NULL); END;
INSERT INTO change_journal_coverage VALUES('funding_program_listings','["id", "source", "external_id", "organization_id", "agency_organization_id", "source_slug", "compass_url", "program_name", "agency_label", "url", "program_description", "is_accepting_applications", "is_recurring", "data_quality", "funding_source", "geographic_scope", "assistance_description", "business_stage", "max_amount_int", "max_amount_str", "application_deadline_string", "application_deadline_date", "application_process_overview", "program_audience", "use_of_funds", "geographic_eligibility", "contact_name", "contact_email", "contact_phone", "source_count", "source_created_at", "source_updated_at", "retrieved_at", "source_sha256"]','[]');
CREATE TRIGGER "journal_funding_program_listings_insert" AFTER INSERT ON "funding_program_listings"
WHEN NOT EXISTS(SELECT 1 FROM organization_replica_state WHERE source IS NOT NULL)
BEGIN INSERT INTO change_journal(table_name,record_key,operation,before_json,after_json)
 VALUES('funding_program_listings',json_object('id',NEW."id"),'insert',NULL,json_object('id',NEW."id",'source',NEW."source",'external_id',NEW."external_id",'organization_id',NEW."organization_id",'agency_organization_id',NEW."agency_organization_id",'source_slug',NEW."source_slug",'compass_url',NEW."compass_url",'program_name',NEW."program_name",'agency_label',NEW."agency_label",'url',NEW."url",'program_description',NEW."program_description",'is_accepting_applications',NEW."is_accepting_applications",'is_recurring',NEW."is_recurring",'data_quality',NEW."data_quality",'funding_source',NEW."funding_source",'geographic_scope',NEW."geographic_scope",'assistance_description',NEW."assistance_description",'business_stage',NEW."business_stage",'max_amount_int',NEW."max_amount_int",'max_amount_str',NEW."max_amount_str",'application_deadline_string',NEW."application_deadline_string",'application_deadline_date',NEW."application_deadline_date",'application_process_overview',NEW."application_process_overview",'program_audience',NEW."program_audience",'use_of_funds',NEW."use_of_funds",'geographic_eligibility',NEW."geographic_eligibility",'contact_name',NEW."contact_name",'contact_email',NEW."contact_email",'contact_phone',NEW."contact_phone",'source_count',NEW."source_count",'source_created_at',NEW."source_created_at",'source_updated_at',NEW."source_updated_at",'retrieved_at',NEW."retrieved_at",'source_sha256',NEW."source_sha256")); END;
CREATE TRIGGER "journal_funding_program_listings_update" AFTER UPDATE ON "funding_program_listings"
WHEN NOT EXISTS(SELECT 1 FROM organization_replica_state WHERE source IS NOT NULL) AND NOT(OLD."id" IS NEW."id" AND OLD."source" IS NEW."source" AND OLD."external_id" IS NEW."external_id" AND OLD."organization_id" IS NEW."organization_id" AND OLD."agency_organization_id" IS NEW."agency_organization_id" AND OLD."source_slug" IS NEW."source_slug" AND OLD."compass_url" IS NEW."compass_url" AND OLD."program_name" IS NEW."program_name" AND OLD."agency_label" IS NEW."agency_label" AND OLD."url" IS NEW."url" AND OLD."program_description" IS NEW."program_description" AND OLD."is_accepting_applications" IS NEW."is_accepting_applications" AND OLD."is_recurring" IS NEW."is_recurring" AND OLD."data_quality" IS NEW."data_quality" AND OLD."funding_source" IS NEW."funding_source" AND OLD."geographic_scope" IS NEW."geographic_scope" AND OLD."assistance_description" IS NEW."assistance_description" AND OLD."business_stage" IS NEW."business_stage" AND OLD."max_amount_int" IS NEW."max_amount_int" AND OLD."max_amount_str" IS NEW."max_amount_str" AND OLD."application_deadline_string" IS NEW."application_deadline_string" AND OLD."application_deadline_date" IS NEW."application_deadline_date" AND OLD."application_process_overview" IS NEW."application_process_overview" AND OLD."program_audience" IS NEW."program_audience" AND OLD."use_of_funds" IS NEW."use_of_funds" AND OLD."geographic_eligibility" IS NEW."geographic_eligibility" AND OLD."contact_name" IS NEW."contact_name" AND OLD."contact_email" IS NEW."contact_email" AND OLD."contact_phone" IS NEW."contact_phone" AND OLD."source_count" IS NEW."source_count" AND OLD."source_created_at" IS NEW."source_created_at" AND OLD."source_updated_at" IS NEW."source_updated_at" AND OLD."retrieved_at" IS NEW."retrieved_at" AND OLD."source_sha256" IS NEW."source_sha256")
BEGIN INSERT INTO change_journal(table_name,record_key,operation,before_json,after_json)
 VALUES('funding_program_listings',json_object('id',NEW."id"),'update',json_object('id',OLD."id",'source',OLD."source",'external_id',OLD."external_id",'organization_id',OLD."organization_id",'agency_organization_id',OLD."agency_organization_id",'source_slug',OLD."source_slug",'compass_url',OLD."compass_url",'program_name',OLD."program_name",'agency_label',OLD."agency_label",'url',OLD."url",'program_description',OLD."program_description",'is_accepting_applications',OLD."is_accepting_applications",'is_recurring',OLD."is_recurring",'data_quality',OLD."data_quality",'funding_source',OLD."funding_source",'geographic_scope',OLD."geographic_scope",'assistance_description',OLD."assistance_description",'business_stage',OLD."business_stage",'max_amount_int',OLD."max_amount_int",'max_amount_str',OLD."max_amount_str",'application_deadline_string',OLD."application_deadline_string",'application_deadline_date',OLD."application_deadline_date",'application_process_overview',OLD."application_process_overview",'program_audience',OLD."program_audience",'use_of_funds',OLD."use_of_funds",'geographic_eligibility',OLD."geographic_eligibility",'contact_name',OLD."contact_name",'contact_email',OLD."contact_email",'contact_phone',OLD."contact_phone",'source_count',OLD."source_count",'source_created_at',OLD."source_created_at",'source_updated_at',OLD."source_updated_at",'retrieved_at',OLD."retrieved_at",'source_sha256',OLD."source_sha256"),json_object('id',NEW."id",'source',NEW."source",'external_id',NEW."external_id",'organization_id',NEW."organization_id",'agency_organization_id',NEW."agency_organization_id",'source_slug',NEW."source_slug",'compass_url',NEW."compass_url",'program_name',NEW."program_name",'agency_label',NEW."agency_label",'url',NEW."url",'program_description',NEW."program_description",'is_accepting_applications',NEW."is_accepting_applications",'is_recurring',NEW."is_recurring",'data_quality',NEW."data_quality",'funding_source',NEW."funding_source",'geographic_scope',NEW."geographic_scope",'assistance_description',NEW."assistance_description",'business_stage',NEW."business_stage",'max_amount_int',NEW."max_amount_int",'max_amount_str',NEW."max_amount_str",'application_deadline_string',NEW."application_deadline_string",'application_deadline_date',NEW."application_deadline_date",'application_process_overview',NEW."application_process_overview",'program_audience',NEW."program_audience",'use_of_funds',NEW."use_of_funds",'geographic_eligibility',NEW."geographic_eligibility",'contact_name',NEW."contact_name",'contact_email',NEW."contact_email",'contact_phone',NEW."contact_phone",'source_count',NEW."source_count",'source_created_at',NEW."source_created_at",'source_updated_at',NEW."source_updated_at",'retrieved_at',NEW."retrieved_at",'source_sha256',NEW."source_sha256")); END;
CREATE TRIGGER "journal_funding_program_listings_delete" AFTER DELETE ON "funding_program_listings"
WHEN NOT EXISTS(SELECT 1 FROM organization_replica_state WHERE source IS NOT NULL)
BEGIN INSERT INTO change_journal(table_name,record_key,operation,before_json,after_json)
 VALUES('funding_program_listings',json_object('id',OLD."id"),'delete',json_object('id',OLD."id",'source',OLD."source",'external_id',OLD."external_id",'organization_id',OLD."organization_id",'agency_organization_id',OLD."agency_organization_id",'source_slug',OLD."source_slug",'compass_url',OLD."compass_url",'program_name',OLD."program_name",'agency_label',OLD."agency_label",'url',OLD."url",'program_description',OLD."program_description",'is_accepting_applications',OLD."is_accepting_applications",'is_recurring',OLD."is_recurring",'data_quality',OLD."data_quality",'funding_source',OLD."funding_source",'geographic_scope',OLD."geographic_scope",'assistance_description',OLD."assistance_description",'business_stage',OLD."business_stage",'max_amount_int',OLD."max_amount_int",'max_amount_str',OLD."max_amount_str",'application_deadline_string',OLD."application_deadline_string",'application_deadline_date',OLD."application_deadline_date",'application_process_overview',OLD."application_process_overview",'program_audience',OLD."program_audience",'use_of_funds',OLD."use_of_funds",'geographic_eligibility',OLD."geographic_eligibility",'contact_name',OLD."contact_name",'contact_email',OLD."contact_email",'contact_phone',OLD."contact_phone",'source_count',OLD."source_count",'source_created_at',OLD."source_created_at",'source_updated_at',OLD."source_updated_at",'retrieved_at',OLD."retrieved_at",'source_sha256',OLD."source_sha256"),NULL); END;
INSERT INTO change_journal_coverage VALUES('funding_program_properties','["listing_id", "field", "position", "value", "value_type"]','[]');
CREATE TRIGGER "journal_funding_program_properties_insert" AFTER INSERT ON "funding_program_properties"
WHEN NOT EXISTS(SELECT 1 FROM organization_replica_state WHERE source IS NOT NULL)
BEGIN INSERT INTO change_journal(table_name,record_key,operation,before_json,after_json)
 VALUES('funding_program_properties',json_object('listing_id',NEW."listing_id",'field',NEW."field",'position',NEW."position"),'insert',NULL,json_object('listing_id',NEW."listing_id",'field',NEW."field",'position',NEW."position",'value',NEW."value",'value_type',NEW."value_type")); END;
CREATE TRIGGER "journal_funding_program_properties_update" AFTER UPDATE ON "funding_program_properties"
WHEN NOT EXISTS(SELECT 1 FROM organization_replica_state WHERE source IS NOT NULL) AND NOT(OLD."listing_id" IS NEW."listing_id" AND OLD."field" IS NEW."field" AND OLD."position" IS NEW."position" AND OLD."value" IS NEW."value" AND OLD."value_type" IS NEW."value_type")
BEGIN INSERT INTO change_journal(table_name,record_key,operation,before_json,after_json)
 VALUES('funding_program_properties',json_object('listing_id',NEW."listing_id",'field',NEW."field",'position',NEW."position"),'update',json_object('listing_id',OLD."listing_id",'field',OLD."field",'position',OLD."position",'value',OLD."value",'value_type',OLD."value_type"),json_object('listing_id',NEW."listing_id",'field',NEW."field",'position',NEW."position",'value',NEW."value",'value_type',NEW."value_type")); END;
CREATE TRIGGER "journal_funding_program_properties_delete" AFTER DELETE ON "funding_program_properties"
WHEN NOT EXISTS(SELECT 1 FROM organization_replica_state WHERE source IS NOT NULL)
BEGIN INSERT INTO change_journal(table_name,record_key,operation,before_json,after_json)
 VALUES('funding_program_properties',json_object('listing_id',OLD."listing_id",'field',OLD."field",'position',OLD."position"),'delete',json_object('listing_id',OLD."listing_id",'field',OLD."field",'position',OLD."position",'value',OLD."value",'value_type',OLD."value_type"),NULL); END;
