import { useEffect, useMemo, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { loadNetworkViewData, type NetworkData } from '../../features/ecosystem/networkViewData'
import { useNetworkViewport } from '../../features/ecosystem/useNetworkViewport'
import { companyKey, compileFunding, fundingCsv, fundingSummary, type FundingRound } from '../../features/ecosystem/fundingStatistics'
import research from '../../features/ecosystem/funding-research.json'
import '../../features/ecosystem/network.css'
import './series-a-funding.css'
const money = (n: number | null | undefined) => n == null ? 'Undisclosed' : new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(n)
export function SeriesAFundingGapPage() {
 const root=useRef<HTMLDivElement>(null);useNetworkViewport(root)
 const [data,setData]=useState<NetworkData|null>(null),[error,setError]=useState(''),[scope,setScope]=useState('all'),[query,setQuery]=useState(''),[stage,setStage]=useState('all'),[asOf,setAsOf]=useState(new Date().toISOString().slice(0,10))
 useEffect(()=>{document.title='Series A Funding Gap · Company funding statistics';const abort=new AbortController();void loadNetworkViewData('relationships',abort.signal).then(d=>{if(!abort.signal.aborted)setData(d)}).catch(()=>{if(!abort.signal.aborted)setError('Funding evidence could not load. Reload to try again.')});return()=>abort.abort()},[])
 const companies=useMemo(()=>data?compileFunding(data.organizations,data.financing.filter((r):r is FundingRound=>Boolean(r&&typeof r==='object'&&'recipient' in r&&'type' in r&&'sourceUrl' in r)),research.rounds,asOf):[],[data,asOf])
 const cohort=companies.filter(c=>scope==='all'||(scope==='portal'?c.portal:research.rounds.some(r=>companyKey(r.recipient)===companyKey(c.name))))
 const summary=fundingSummary(cohort)
 const visible=cohort.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())&&(stage==='all'||(stage==='seed'?c.stageRank>0&&c.stageRank<=2:stage==='a'?c.stageRank===3:stage==='later'?c.stageRank>3:c.stageRank===0)))
 const download=()=>{const url=URL.createObjectURL(new Blob([fundingCsv(visible)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`series-a-funding-gap-${asOf}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <div ref={root} className="portal-ecosystem eco-page eco-secondary-view funding-gap">
 <header className="eco-network-heading"><h1>Series A Funding Gap</h1><nav aria-label="Network views"><Link to="/ecosystem/network">Graph</Link><Link to="/ecosystem/network/events">Events</Link><Link to="/ecosystem/network/relationships">Relationships</Link><Link to="/ecosystem/network/funding" aria-current="page">Funding gap</Link><Link to="/ecosystem/network/help">Sources &amp; help</Link></nav></header>
 <section className="eco-view-content" tabIndex={0} aria-label="Company funding statistics">
 <p>Compare each company’s highest documented funding stage and largest disclosed round. Investigate the transition from seed financing to Series A.</p>
 <div className="eco-view-filters"><label>Company sample<select value={scope} onChange={e=>setScope(e.target.value)}><option value="all">Portal companies + reviewed regional sample</option><option value="portal">Portal companies only</option><option value="reviewed">Reviewed regional sample only</option></select></label><label>Evidence through<input type="date" max={new Date().toISOString().slice(0,10)} value={asOf} onChange={e=>{if(e.target.value)setAsOf(e.target.value)}} /></label></div>
 {!data?<p role="status">{error||'Loading funding evidence…'}</p>:<>
 <p className="eco-note">Public evidence {data.offline?'saved; refresh unavailable; last checked':'checked'} {new Date(data.lastCheckedAt!).toLocaleString()}. Regional sources reviewed {research.reviewedAt}. Selected evidence sample, not a regional census.</p>
 <div className="funding-metrics" aria-label="Cohort statistics">{[[summary.total,'Companies in sample'],[summary.known,'Documented funding stage'],[summary.seedOnly,'Seed / pre-seed; no A documented'],[summary.atA,'Highest stage: Series A'],[summary.beyondA,'Highest stage: Series B or later'],[summary.unknown,'Funding stage unknown']].map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div>
 <h2>Highest documented stage</h2><div className="funding-stage-chart" aria-label="Stage distribution">{[[summary.seedOnly,'Seed / pre-seed','seed'],[summary.atA,'Series A','a'],[summary.beyondA,'Series B+','later'],[summary.unknown,'Unknown','unknown']].map(([v,l,s])=><button key={l} type="button" onClick={()=>setStage(String(s))} aria-label={`Filter ${l}: ${v} companies`}><span>{l}</span><meter min={0} max={Math.max(1,summary.total)} value={Number(v)}>{v}</meter><strong>{v}</strong></button>)}</div>
 <p><strong>Series A round size:</strong> median {summary.seriesAMedian===null?'unavailable':money(summary.seriesAMedian)} across {summary.seriesAAmountCount} companies with disclosed USD Series A amounts. {summary.seriesAAmountCount>0&&<>Range {money(summary.seriesAMin)}–{money(summary.seriesAMax)}.</>} Each company contributes its largest documented Series A round, including extensions.</p>
 <p><strong>Observed seed → A interval:</strong> {summary.transitionMedian===null?'unavailable':`${summary.transitionMedian} months median`}, from {summary.transitionCount} companies with both dated seed and A evidence. This is not a conversion rate; a company without a documented A is not counted as a failure.</p>
 <details className="funding-method"><summary>Method and what would establish a funding gap</summary><p>Stages follow explicit labels, not dollar size. A-1, A-2 and A extensions remain Series A; B1/B2 remain Series B. Grants, prizes, debt, accelerator terms, fund capitalization, cumulative company totals, and fundraising targets are excluded. USD statistics omit undisclosed or non-USD amounts. Closing updates for the same identified round are collapsed. Amounts are never summed.</p><p>Unknown means no qualifying round in these sources, not unfunded. Seed without documented A is a research queue, not proof of stalled fundraising. Estimating a funding gap requires a defined seed cohort, complete later-round histories, company status, and comparable observation windows. This snapshot cannot establish the gap’s size or cause.</p><p>{research.scope} Regional records may include companies with multiple locations. The cutoff filters round dates, not historical company membership or information contained in sources published later.</p></details>
 <div className="eco-view-filters"><label>Find a company<input type="search" value={query} onChange={e=>setQuery(e.target.value)} /></label><label>Highest stage<select value={stage} onChange={e=>setStage(e.target.value)}><option value="all">All stages</option><option value="seed">Seed / pre-seed; no A documented</option><option value="a">Series A</option><option value="later">Series B or later</option><option value="unknown">Unknown</option></select></label><button type="button" onClick={download}>Export visible companies CSV</button></div>
 <p role="status">Showing {visible.length} of {cohort.length} companies. Summary statistics use the selected company sample and date cutoff.</p>
 <div className="eco-table-scroll"><table className="eco-table"><caption>Company funding evidence — highest stage and largest disclosed USD round</caption><thead><tr><th>Company / scope</th><th>Highest documented stage</th><th>Largest disclosed round</th><th>Evidence and qualifications</th></tr></thead><tbody>{visible.map(c=><tr key={c.id}><td><strong>{c.name}</strong><small>{c.portal?'Portal company':'Regional research'}{c.region&&` · ${c.region}`}</small></td><td>{c.stage}<small>{c.highest?.type} {c.highest?.date}</small>{c.highest&&<a href={c.highest.sourceUrl} target="_blank" rel="noopener noreferrer">Stage source ↗</a>}</td><td>{money(c.largest?.amount)}<small>{c.largest?.type} {c.largest?.date}</small></td><td>{c.largest&&<a href={c.largest.sourceUrl} target="_blank" rel="noopener noreferrer">Amount source ↗</a>}<small>{c.largest?.evidence||c.highest?.evidence}</small><p>{c.largest?.notes||c.highest?.notes||(c.stageRank===0?'No qualifying round documented in these sources.':'Highest stage in available evidence; later rounds may be missing.')}</p>{c.seedToAMonths!==null&&<small>Observed seed → A: {c.seedToAMonths} months</small>}</td></tr>)}</tbody></table></div>
 </>}
 </section></div>
}
