events {}
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  server {
    listen 8080;
    server_name _;
    root /directory;
    add_header Cache-Control "no-store" always;
    location = /inventory.json { alias /inventory/inventory.json; }
    location / { try_files $uri $uri/ =404; }
  }
}
