import { VenueVotes } from './VenueVotes'
import { useEffect, useState } from 'react'
import { VenueSearch } from './VenueSearch'
import { useAuth } from '../../app/AppProviders'
export type Venue = {id:string;name:string;description?:string|null;image_url?:string|null;image_source_url?:string|null;image_credit?:string|null;research_url?:string|null;researched_at?:string|null;address?:string|null;website?:string|null;amenities?:string|null;capacity?:string|null;cost?:string|null;opening_hours?:string|null;status:string;category?:string;event_status?:string}
export function EventVenues({eventId,venues,canManage,onSaved}:{eventId:string;venues:Venue[];canManage:boolean;onSaved:(venues:Venue[])=>void}){
 const {token}=useAuth(),[catalog,setCatalog]=useState<Venue[]>([]),[selected,setSelected]=useState<string[]>(venues.map(v=>v.id)),[confirmed,setConfirmed]=useState(venues.find(v=>v.event_status==='confirmed')?.id||''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{setSelected(venues.map(v=>v.id));setConfirmed(venues.find(v=>v.event_status==='confirmed')?.id||'')},[venues])
 useEffect(()=>{if(canManage)fetch('/api/org/api/network/venues/public').then(r=>{if(!r.ok)throw new Error('Unable to load venues');return r.json()}).then(setCatalog).catch(e=>setMessage(e.message))},[canManage])
 async function save(){setBusy(true);setMessage('');try{const r=await fetch(`/api/org/api/network/events/${eventId}/venues`,{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({candidate_venue_ids:selected,confirmed_venue_id:confirmed||null})});if(!r.ok)throw new Error(await r.text());onSaved((await r.json()).venues);setMessage('Venues saved.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to save venues')}finally{setBusy(false)}}
 return <section className="portal-card" style={{display:'grid',gap:8}}><h2>Event venues</h2><VenueVotes eventId={eventId} venues={venues}/><VenueSearch/>{canManage&&<details><summary>Choose candidate venues</summary><div style={{maxHeight:240,overflow:'auto'}}>{catalog.filter(v=>v.status==='active').map(v=><label key={v.id} style={{display:'flex',gap:8,padding:5}}><input type="checkbox" checked={selected.includes(v.id)} onChange={e=>{setSelected(e.target.checked?[...selected,v.id]:selected.filter(id=>id!==v.id));if(!e.target.checked&&confirmed===v.id)setConfirmed('')}}/>{v.name}</label>)}</div><label>Confirmed venue<select value={confirmed} onChange={e=>setConfirmed(e.target.value)}><option value="">Not confirmed</option>{catalog.filter(v=>selected.includes(v.id)).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><button disabled={busy} onClick={()=>void save()}>Save venues</button></details>}{message&&<p role="status">{message}</p>}</section>
}
