import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useAuth } from '../../../app/AppProviders'
import { VenueProfile } from './VenueProfile'
import './venues.css'
import type { Venue } from '../../components/EventVenues'
export function VenuesPage(){
 const {id}=useParams(),{token}=useAuth(),[venues,setVenues]=useState<Venue[]>([]),[q,setQ]=useState(''),[message,setMessage]=useState(''),[draft,setDraft]=useState<Record<string,string>>({}),[editing,setEditing]=useState(!id)
 async function load(){try{const r=await fetch('/api/org/api/network/venues/public'+(id?`/${id}`:''));if(!r.ok)throw new Error('Unable to load venues');const data=await r.json();setVenues(id?[data]:data)}catch(e){setMessage(String(e))}}
 useEffect(()=>{void load()},[id])
 async function edit(){const r=await fetch(`/api/org/api/network/venues/${id}/manage`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok){setMessage('Only the venue owner or an organization administrator can edit this venue.');return}const row=await r.json();setDraft(Object.fromEntries(['description','image_url','image_source_url','image_credit','research_url','researched_at','name','address','website','amenities','capacity','cost','opening_hours','category','status','contact_name','contact_email','contact_phone','notes'].map(k=>[k,row[k]||''])));setEditing(true)}
 async function save(){try{const r=await fetch('/api/org/api/network/venues'+(id?`/${id}`:''),{method:id?'PATCH':'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({...draft,status:draft.status||'active',category:draft.category||'indoor'})});if(!r.ok)throw new Error(await r.text());setMessage('Venue saved.');setDraft({});setEditing(!id);await load()}catch(e){setMessage(String(e))}}
 return <main className="venue-page" style={{display:'grid',gap:16}}><nav className="venue-breadcrumbs" aria-label="Breadcrumb"><Link to="/">Home</Link><span>/</span><Link to="/orgs/events/venues">Venues</Link>{id&&<><span>/</span><span>{venues[0]?.name||'Venue'}</span></>}</nav>{!id&&<h1>Find a venue</h1>}{message&&<p role="status">{message}</p>}{!id&&<label>Search venues<input value={q} onChange={e=>setQ(e.target.value)}/></label>}{id ? venues[0] && <VenueProfile venue={venues[0]} /> : <div className="venue-directory">{venues.filter(v=>`${v.name} ${v.address||''}`.toLowerCase().includes(q.toLowerCase())).map(v=><Link className="portal-card venue-directory-card" key={v.id} to={`/orgs/events/venues/${encodeURIComponent(v.id)}`}><div className="venue-directory-image">{v.image_url?<img src={v.image_url} alt="" loading="lazy"/>:<span>{v.name.slice(0,1)}</span>}</div><div><h2>{v.name}</h2><p className="muted">{v.address||'Address not yet provided'}</p>{v.description&&<p>{v.description}</p>}</div></Link>)}</div>}{token&&id&&!editing&&<button onClick={()=>void edit()}>Edit venue</button>}{token&&editing&&<form className="portal-card" onSubmit={e=>{e.preventDefault();void save()}} style={{display:'grid',gap:8}}><h2>{id?'Edit venue':'Add venue'}</h2>{['description','image_url','image_source_url','image_credit','research_url','researched_at','name','address','website','amenities','capacity','cost','opening_hours','contact_name','contact_email','contact_phone','notes'].map(k=><label key={k}>{k.replaceAll('_',' ')}<input required={k==='name'} value={draft[k]||''} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}<label>Status<select value={draft.status||'active'} onChange={e=>setDraft({...draft,status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><p className="muted">Contact details and notes are visible only to venue managers.</p><button>Save venue</button></form>}</main>
}
