import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useAuth } from '../../../app/AppProviders'
import type { Venue } from '../../components/EventVenues'
export function VenuesPage(){
 const {id}=useParams(),{token}=useAuth(),[venues,setVenues]=useState<Venue[]>([]),[q,setQ]=useState(''),[message,setMessage]=useState(''),[draft,setDraft]=useState<Record<string,string>>({}),[editing,setEditing]=useState(!id)
 async function load(){try{const r=await fetch('/api/org/api/network/venues/public'+(id?`/${id}`:''));if(!r.ok)throw new Error('Unable to load venues');const data=await r.json();setVenues(id?[data]:data)}catch(e){setMessage(String(e))}}
 useEffect(()=>{void load()},[id])
 async function edit(){const r=await fetch(`/api/org/api/network/venues/${id}/manage`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok){setMessage('Only the venue owner or an organization administrator can edit this venue.');return}const row=await r.json();setDraft(Object.fromEntries(['name','address','website','amenities','capacity','cost','opening_hours','category','status','contact_name','contact_email','contact_phone','notes'].map(k=>[k,row[k]||''])));setEditing(true)}
 async function save(){try{const r=await fetch('/api/org/api/network/venues'+(id?`/${id}`:''),{method:id?'PATCH':'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({...draft,status:draft.status||'active',category:draft.category||'indoor'})});if(!r.ok)throw new Error(await r.text());setMessage('Venue saved.');setDraft({});setEditing(!id);await load()}catch(e){setMessage(String(e))}}
 return <main className="panel" style={{display:'grid',gap:16}}><h1>{id?venues[0]?.name||'Venue':'Event venues'}</h1><nav><Link to="/orgs/events">Manage events</Link> · <Link to="/orgs/events/venues">All venues</Link></nav>{message&&<p role="status">{message}</p>}{!id&&<label>Search venues<input value={q} onChange={e=>setQ(e.target.value)}/></label>}{venues.filter(v=>`${v.name} ${v.address||''}`.toLowerCase().includes(q.toLowerCase())).map(v=><article className="portal-card" key={v.id}><h2><Link to={`/orgs/events/venues/${v.id}`}>{v.name}</Link></h2><p>{v.address||'Address not yet provided'}</p><p>{v.amenities}</p>{v.capacity&&<p>Capacity: {v.capacity}</p>}{v.cost&&<p>Cost: {v.cost}</p>}{v.opening_hours&&<p>Hours: {v.opening_hours}</p>}<p>{v.category} · {v.status}</p>{v.website&&<a href={v.website} target="_blank" rel="noreferrer">Website</a>}</article>)}{token&&id&&!editing&&<button onClick={()=>void edit()}>Edit venue</button>}{token&&editing&&<form className="portal-card" onSubmit={e=>{e.preventDefault();void save()}} style={{display:'grid',gap:8}}><h2>{id?'Edit venue':'Add venue'}</h2>{['name','address','website','amenities','capacity','cost','opening_hours','contact_name','contact_email','contact_phone','notes'].map(k=><label key={k}>{k.replaceAll('_',' ')}<input required={k==='name'} value={draft[k]||''} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}<label>Status<select value={draft.status||'active'} onChange={e=>setDraft({...draft,status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><p className="muted">Contact details and notes are visible only to venue managers.</p><button>Save venue</button></form>}</main>
}
