#!/usr/bin/env python3
"""Generate reviewed journal triggers from the primary schema through migration 0072."""
import argparse
import json
import re
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXCLUDED = {
    'organization_replica_state': 'replication bookkeeping',
    'email_oauth_states': 'temporary authentication secrets',
    'email_send_attempts': 'rate limiting',
    'event_mcp_rate_limits': 'rate limiting',
    'event_mcp_operations': 'temporary operation receipts',
    'local_newsletter_previews': 'temporary operation receipts',
    'private_newsletter_previews': 'temporary operation receipts',
    'ubi_tick_runs': 'scheduler bookkeeping',
    'ubi_tick_state': 'scheduler bookkeeping',
    'organization_chat_provisioning': 'retry bookkeeping',
    'push_deliveries': 'delivery bookkeeping',
    'email_deliveries': 'delivery bookkeeping',
}


def quote(value):
    return '"' + value.replace('"', '""') + '"'


def literal(value):
    return "'" + value.replace("'", "''") + "'"


def generate():
    db = sqlite3.connect(':memory:')
    for path in sorted((ROOT / 'org-worker/migrations').glob('*.sql')):
        if int(path.name.split('_')[0]) <= 72:
            db.executescript(path.read_text())
    sql = ["""-- Generated by scripts/generate-change-journal.py; schema through 0072.
-- Every captured mutation and its journal entry commit or roll back together.
-- Replicated public snapshots are excluded on local replicas; local newsletter
-- writes still retain their journal. No public API exposes this journal.
CREATE TABLE change_journal_source (
 id INTEGER PRIMARY KEY CHECK(id=1),
 source_id TEXT NOT NULL,
 created_at TEXT NOT NULL DEFAULT(strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
INSERT INTO change_journal_source(id,source_id) VALUES(1,lower(hex(randomblob(16))));
CREATE TABLE change_journal (
 sequence INTEGER PRIMARY KEY AUTOINCREMENT,
 table_name TEXT NOT NULL,
 record_key TEXT NOT NULL CHECK(json_valid(record_key)),
 operation TEXT NOT NULL CHECK(operation IN ('insert','update','delete')),
 before_json TEXT CHECK(before_json IS NULL OR json_valid(before_json)),
 after_json TEXT CHECK(after_json IS NULL OR json_valid(after_json)),
 recorded_at TEXT NOT NULL DEFAULT(strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX change_journal_record ON change_journal(table_name,record_key,sequence);
CREATE TRIGGER change_journal_no_update BEFORE UPDATE ON change_journal
BEGIN SELECT RAISE(ABORT,'Change journal is append-only'); END;
CREATE TRIGGER change_journal_no_delete BEFORE DELETE ON change_journal
BEGIN SELECT RAISE(ABORT,'Change journal is append-only'); END;
CREATE TABLE change_journal_coverage (
 table_name TEXT PRIMARY KEY,
 columns_json TEXT NOT NULL CHECK(json_valid(columns_json)),
 redacted_json TEXT NOT NULL CHECK(json_valid(redacted_json))
);
CREATE TABLE change_journal_exclusions (table_name TEXT PRIMARY KEY,reason TEXT NOT NULL);
"""]
    for name, reason in sorted(EXCLUDED.items()):
        sql.append(f'INSERT INTO change_journal_exclusions VALUES({literal(name)},{literal(reason)});')
    tables = db.execute("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").fetchall()
    for (table,) in tables:
        if table in EXCLUDED:
            continue
        columns = db.execute('PRAGMA table_info(' + quote(table) + ')').fetchall()
        names = [col[1] for col in columns]
        redacted = [name for name in names if re.search(r'token|secret|password|verifier|nonce|browser_hash|^p256dh$|^auth$|^endpoint$', name, re.I)]
        keys = [col[1] for col in sorted(columns, key=lambda col: col[5]) if col[5]] or ['rowid']
        sql.append(f'INSERT INTO change_journal_coverage VALUES({literal(table)},{literal(json.dumps(names))},{literal(json.dumps(redacted))});')

        def snapshot(prefix):
            args = []
            for name in names:
                args.extend([literal(name), "'[REDACTED]'" if name in redacted else prefix + '.' + quote(name)])
            return 'json_object(' + ','.join(args) + ')'

        local = table in {'ecosystem_sync_changes', 'local_newsletter_imports', 'newsletter_source_archives'}
        guard = '1' if local else 'NOT EXISTS(SELECT 1 FROM organization_replica_state WHERE source IS NOT NULL)'
        for operation in ['insert', 'update', 'delete']:
            prefix = 'OLD' if operation == 'delete' else 'NEW'
            key = 'json_object(' + ','.join(part for name in keys for part in [literal(name), prefix + '.' + quote(name)]) + ')'
            before = 'NULL' if operation == 'insert' else snapshot('OLD')
            after = 'NULL' if operation == 'delete' else snapshot('NEW')
            condition = guard
            if operation == 'update':
                condition += ' AND NOT(' + ' AND '.join('OLD.' + quote(name) + ' IS NEW.' + quote(name) for name in names) + ')'
            sql.append(f'''CREATE TRIGGER {quote('journal_' + table + '_' + operation)} AFTER {operation.upper()} ON {quote(table)}
WHEN {condition}
BEGIN INSERT INTO change_journal(table_name,record_key,operation,before_json,after_json)
 VALUES({literal(table)},{key},{literal(operation)},{before},{after}); END;''')
    db.close()
    return '\n'.join(sql) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', required=True, type=Path)
    args = parser.parse_args()
    args.output.write_text(generate())
