/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=journal.wrangler.jsonc --include-runtime=false --env-interface=JournalStorageBindings journal-bindings.d.ts` (hash: 04930610698fc37fe2c6500500f2b887)
interface __BaseEnv_JournalStorageBindings {
	JOURNAL_DB: D1Database;
	LOCAL_NEWSLETTER_WRITES: string;
	LOCAL_NEWSLETTER_DATASET: string;
	LOCAL_NEWSLETTER_TOKEN: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_JournalStorageBindings {}
}
interface JournalStorageBindings extends __BaseEnv_JournalStorageBindings {}
